version: '3.2'
services:
  weather-app1:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web1                    
      networks:
       - frontend
  weather-app2:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web2
      networks:
       - frontend
  weather-app3:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web3
      networks:
       - frontend

  loadbalancer:
      build: ./loadbalancer
      container_name: load-balancer
      tty: true
      ports:
       - '80:80'
      networks:
       - frontend
  
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - 9090:9090
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      volumes:
        - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      depends_on:
        - weather-app1
        - weather-app2
        - weather-app3
        - loadbalancer

networks:
  frontend: