version: '3.2'
services:
  weather-app1:
      image: mehdijebali/widgetfactory:1.1.1
      networks:
       - frontend
  weather-app2:
      image: mehdijebali/widgetfactory:1.1.1
      networks:
       - frontend
  weather-app3:
      image: mehdijebali/widgetfactory:1.1.1
      networks:
       - frontend

  loadbalancer:
      build: ./loadbalancer
      tty: true
      ports:
       - '80:80'
      networks:
       - frontend

networks:
  frontend: