version: '3.2'
services:
  web1:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web1                    
      networks:
       - frontend
  web2:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web2
      networks:
       - frontend
  web3:
      image: mehdijebali/widgetfactory:1.1.1
      container_name: web3
      networks:
       - frontend

  load-balancer:
      build: ./loadbalancer
      container_name: load-balancer
      tty: true
      ports:
       - '80:80'
      networks:
       - frontend
  
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - 9090:9090
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      volumes:
        - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      depends_on:
        - web1
        - web2
        - web3
        - load-balancer

networks:
  frontend: